version: "3"

services:
  luminus:
    image: hkim0331/luminus:0.1
    user: vscode
    # ports:
    #   - "3000:3000"
    volumes:
      - .:/usr/src/app
      - m2:/home/vscode/.m2
      - gitlibs:/home/vscode/.gitlibs
    working_dir: /usr/src/app
    entrypoint:
      - sleep
      - infinity

  db:
    image: postgres
    # restart: always
    environment:
      POSTGRES_DB: wil
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
      TZ: Asia/Toky
    # ports:
    #   - "55432:5432"
   volumes:
      # - ./initdb.d:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data

volumes:
  gitlibs:
    external: true
  m2:
    external: true
  data:
    driver: local
