version: "3.9"

services:
  clojure:
    image: hkim0331/clj-cljs
    ports:
      - "3020:3000"
      - "9630:9630"
    volumes:
      - .:/usr/src/app:cached
      - m2:/root/.m2
    working_dir: /usr/src/app
    command: /bin/sh -c "while sleep 1000; do :; done"

  postgres:
    image: postgres
    environmemt:
      POSTGRES_DB: wil
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
    volumes:
      data: /var/lib/postgresql/data


volumes:
  m2:
    external: true
  data:
    driver: local
